language: php
php:
  - 7.2
  - 7.3
  - 7.4
env:
  - COMPOSER_MEMORY_LIMIT=-1 COMPOSER_MIRROR_PATH_REPOS=1
before_install:
  - cd ~
  - composer create-project drupal/recommended-project:^8.9 module-test --no-interaction
  - cd module-test
  - composer config repositories.manati_ckeditor path $TRAVIS_BUILD_DIR
  - composer config extra.enable-patching true
  - composer require drush/drush
before_script:
  - cd ~/module-test
  - composer require manaticr/manati_ckeditor:"*"
script:
  - ./vendor/bin/drush si standard -y --db-url=sqlite://tmp/.ht.sqlite
  - ./vendor/bin/drush en manati_ckeditor -y
